- name: "Installing nginx server"
  hosts: local
  connection: local
  vars_files:
    - course.yaml
  tasks:
    - name: Displaying course information
      ansible.builtin.debug:
        msg: "thec course is {{COURSE}} and Trainse is {{TRAINER}} and Duration is {{DURATION}}"
    
    