- name: "Installing nginx server"
  hosts: local
  connection: local
  become: yes
  vars_files:
    - course.yaml
  tasks:
    - name: Displaying course information
      msg: thec course is {{COURSE}} and Trainse is {{TRAINER}} and Duration is {{DURATION}}
    
    